DELETE FROM _user WHERE _role = 'ROLE02';
DELETE FROM _house_work_temp;
DELETE FROM _contract_temp;
DELETE FROM _contract_details;
DELETE FROM _client_payment;
DELETE FROM _client_contract;
DELETE FROM _house_details;
DELETE FROM _work;
DELETE FROM _house;
DELETE FROM _client;
DELETE FROM _unit;
DELETE FROM _location;